version: '3.3'

services:
  nszu-news:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  postgresql:
    restart: always
    container_name: postgresql
    image: postgres:latest
    env_file: .env-news
    ports:
      - "5432:5432"
    volumes:
      - postgresql_db:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB={POSTGRES_DB}
     - POSTGRES_USER={POSTGRES_USER}
     - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      
volumes:
  postgresql_db:  